#
# TABLE STRUCTURE FOR: round_diamonds
#

DROP TABLE IF EXISTS `round_diamonds`;

CREATE TABLE `round_diamonds` (
  `key_id` int(11) NOT NULL AUTO_INCREMENT,
  `shape` varchar(255) NOT NULL DEFAULT 'BR',
  `lab` varchar(3) NOT NULL DEFAULT 'GIA',
  `size` float DEFAULT NULL,
  `color` varchar(255) DEFAULT NULL,
  `clarity` varchar(255) DEFAULT NULL,
  `giadate` date DEFAULT NULL,
  `gianumber` varchar(255) DEFAULT NULL,
  `measurements` varchar(255) DEFAULT NULL,
  `ratio` float DEFAULT -0,
  `depth` int(5) DEFAULT NULL,
  `table` int(5) DEFAULT NULL,
  `girdle` varchar(255) DEFAULT NULL,
  `cut` varchar(255) DEFAULT NULL,
  `polish` varchar(255) DEFAULT NULL,
  `symmetry` varchar(255) DEFAULT NULL,
  `culet` varchar(255) DEFAULT NULL,
  `fluorescence` varchar(255) DEFAULT NULL,
  `comments` varchar(255) DEFAULT NULL,
  `pricepercarat` float DEFAULT NULL,
  `orgprice` float DEFAULT NULL,
  `disc` float DEFAULT NULL,
  `person` varchar(255) DEFAULT NULL,
  `datebought` date DEFAULT NULL,
  `datesold` date DEFAULT NULL,
  `soldby` varchar(255) DEFAULT NULL,
  `rapaport_shape` varchar(10) DEFAULT 'BR',
  `orig_disc` float DEFAULT NULL,
  PRIMARY KEY (`key_id`)
) ENGINE=MyISAM AUTO_INCREMENT=101 DEFAULT CHARSET=utf8;

INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (1, 'EM', ' EG', '99715100', 'f', 'vs1', '1999-10-14', '1017234727', 'vel', '2', 58, 62, 'optio', 'vg', 'g', 'f', 'medium', 'vsb', 'Beatae optio laboriosam in placeat.', '480.494', '10711500', '0', 'v', '1984-04-30', '1996-12-22', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (2, 'PC', ' EG', '96840700', 'j', 'vs2', '1990-02-23', '1806057393', 'est', '1', 55, 58, 'sequi', 'vg', 'p', 'p', 'small', ' sb', 'Nihil nemo voluptas odit ea.', '768129000', '2320.35', '0', 'v', '1990-02-09', '1988-12-30', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (3, 'PC', ' EG', '663', 'g', 'si2', '2008-08-22', '1553235855', 'eveniet', '1', 58, 70, 'minus', 'ex', 'vg', 'g', 'medium', ' mb', 'Hic est repudiandae dolorem iusto ut voluptatem.', '423.694', '803.694', '0', 'v', '2016-02-17', '1972-02-07', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (4, 'BR', ' EG', '58', 'h', 'vs1', '1987-08-06', '1511086819', 'blanditiis', '2', 54, 61, 'eos', 'ex', 'ex', 'p', 'small', ' sb', 'Voluptatibus tenetur ut a.', '67858.3', '417854', '0', 'v', '1992-06-11', '2011-11-30', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (5, 'MQ', ' EG', '25', 'd', 'fl', '1985-07-13', '1499336240', 'ad', '1', 61, 61, 'inventore', 'g', 'f', 'g', 'large', 'none', 'Qui et et accusamus distinctio earum numquam molestiae.', '371026000', '4641.36', '0', 'v', '2013-06-24', '2007-07-28', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (6, 'PC', ' EG', '3620220', 'd', 'vs2', '1977-08-27', '1288859461', 'qui', '1', 51, 54, 'odit', 'p', 'f', 'f', 'large', ' sb', 'Fuga natus ut consequatur ipsum quo provident soluta.', '10.8619', '4194.6', '0', 'v', '2015-09-03', '1996-04-14', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (7, 'MQ', 'GIA', '244529', 'e', 'fl', '1988-02-05', '1608542112', 'ab', '2', 59, 63, 'fugit', 'ex', 'p', 'f', 'small', 'none', 'Saepe eos nulla nam possimus.', '19539800', '4587.58', '0', 'w', '2005-03-11', '1992-01-27', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (8, 'EM', 'GIA', '2362', 'g', 'vs1', '1995-02-28', '1449306524', 'quo', '1', 68, 58, 'quas', 'vg', 'vg', 'p', 'medium', ' sb', 'Vero nisi facere ea culpa qui.', '497.515', '3542.66', '0', 'w', '1976-06-22', '2007-05-16', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (9, 'MQ', ' EG', '166', 'g', 'if', '1990-10-15', '1424735817', 'delectus', '2', 52, 52, 'tempore', 'f', 'vg', 'ex', 'small', ' sb', 'Sequi voluptatem velit dolor vel possimus.', '496.117', '8104.87', '0', 'v', '2017-10-10', '1976-01-05', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (10, 'BR', ' EG', '1', 'd', 'vvs2', '2016-06-26', '1787623441', 'error', '2', 58, 50, 'enim', 'ex', 'p', 'p', 'none', ' faint', 'Numquam quidem ut dolorem culpa excepturi dolorum occaecati et.', '143394', '529029', '0', 'v', '1976-09-06', '2008-02-20', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (11, 'PC', ' EG', '18', 'f', 'si2', '1997-11-26', '1617320996', 'fugit', '1', 56, 60, 'et', 'f', 'f', 'g', 'large', ' mb', 'Nulla et et enim occaecati.', '282.767', '1578850', '0', 'w', '1994-04-10', '1989-08-12', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (12, 'EM', ' EG', '36190', 'f', 'vs2', '1998-11-10', '1570597311', 'possimus', '1', 56, 55, 'minima', 'f', 'f', 'f', 'small', ' faint', 'Dolorem et beatae provident ad.', '11435.7', '8753170', '0', 'w', '2007-12-11', '1983-09-02', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (13, 'PC', ' EG', '325222', 'd', 'vs2', '1983-11-16', '1986526199', 'et', '1', 61, 60, 'debitis', 'g', 'vg', 'ex', 'medium', ' mb', 'Provident voluptatem totam delectus enim est error ad.', '2631940', '110676000', '0', 'v', '1999-01-09', '2008-11-21', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (14, 'MQ', 'GIA', '6', 'f', 'fl', '1979-09-11', '1682439009', 'eos', '2', 64, 52, 'eligendi', 'p', 'ex', 'vg', 'none', ' faint', 'Fugiat amet enim dolores aut eaque qui non.', '773.529', '397683000', '0', 'v', '1995-09-13', '1979-12-13', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (15, 'PC', 'GIA', '42340300', 'h', 'si2', '2008-10-14', '1253969907', 'distinctio', '1', 57, 57, 'assumenda', 'f', 'p', 'ex', 'large', ' mb', 'Cumque cupiditate asperiores qui quae explicabo ipsum vero odio.', '2138930', '1724550', '0', 'w', '2011-02-01', '1974-12-01', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (16, 'PC', ' EG', '3', 'j', 'fl', '2018-02-05', '1075991725', 'deserunt', '1', 61, 61, 'in', 'p', 'p', 'g', 'large', 'none', 'Esse saepe laudantium perspiciatis non.', '152999', '2587.91', '0', 'w', '2011-04-29', '2001-02-02', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (17, 'PC', ' EG', '21250', 'f', 'si1', '1971-07-01', '1260954797', 'sunt', '2', 55, 69, 'quia', 'ex', 'g', 'p', 'small', 'none', 'Et quis dolor esse et.', '32509.9', '28.5043', '0', 'v', '1978-03-15', '1971-09-12', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (18, 'MQ', 'GIA', '213505', 'g', 'vvs2', '2012-05-31', '1997551067', 'est', '1', 51, 54, 'dolorem', 'p', 'vg', 'g', 'small', ' mb', 'Est porro voluptatum veniam cumque labore ea dolorum.', '604.343', '75760600', '0', 'v', '2000-01-27', '2013-10-20', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (19, 'MQ', ' EG', '6', 'i', 'vs1', '2010-10-19', '1757117921', 'nisi', '2', 50, 62, 'aut', 'g', 'f', 'ex', 'large', ' sb', 'Qui minima sed magnam.', '1914860', '4148.07', '0', 'w', '1984-07-03', '1973-07-07', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (20, 'BR', 'GIA', '30279', 'f', 'if', '1987-07-07', '1227052979', 'aut', '1', 58, 66, 'nesciunt', 'f', 'g', 'vg', 'none', 'none', 'Ducimus molestiae esse ducimus quaerat ut inventore.', '247.707', '1398960', '0', 'w', '1987-11-14', '1979-01-06', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (21, 'PC', 'GIA', '2855', 'g', 'if', '2010-04-17', '1003041634', 'amet', '2', 56, 70, 'minima', 'vg', 'g', 'p', 'none', ' sb', 'Quaerat odit harum blanditiis consequuntur vitae blanditiis.', '10219.1', '5037.4', '0', 'w', '1987-08-12', '2014-07-11', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (22, 'BR', 'GIA', '496384', 'i', 'vs2', '1992-11-09', '1384155759', 'ut', '2', 59, 57, 'unde', 'f', 'g', 'p', 'large', ' mb', 'Dolor aut nostrum magni et impedit sint fugit.', '4092.56', '2993.41', '0', 'v', '1998-08-21', '1970-08-06', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (23, 'PC', 'GIA', '31703', 'f', 'si1', '2016-11-06', '1464635553', 'fugiat', '1', 55, 64, 'earum', 'vg', 'f', 'ex', 'medium', 'none', 'Quo qui porro accusantium temporibus tenetur ad nesciunt.', '209.847', '3641.92', '0', 'w', '2003-03-03', '1994-01-05', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (24, 'EM', ' EG', '7411', 'j', 'vs2', '1981-04-15', '1368068324', 'amet', '2', 57, 50, 'excepturi', 'g', 'vg', 'g', 'none', ' mb', 'Consequuntur non sit delectus vel ut omnis ut qui.', '176483', '228462000', '0', 'w', '1978-11-25', '2001-04-28', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (25, 'MQ', 'GIA', '1320160', 'j', 'vvs1', '1998-09-01', '1554583758', 'tempore', '1', 69, 63, 'saepe', 'g', 'f', 'vg', 'medium', ' mb', 'Minus quis quidem ad incidunt magni.', '116.05', '13245.1', '0', 'v', '2013-12-31', '2009-03-09', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (26, 'BR', ' EG', '272', 'i', 'if', '1991-09-29', '1464928508', 'veniam', '2', 63, 65, 'eius', 'p', 'vg', 'f', 'medium', ' faint', 'Est qui dolores qui quasi dolor et.', '316422', '509411000', '0', 'v', '2003-02-15', '1986-07-20', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (27, 'EM', ' EG', '354', 'd', 'vvs1', '1998-06-29', '1116457295', 'quo', '1', 70, 68, 'fugit', 'ex', 'ex', 'f', 'medium', 'vsb', 'Voluptate odio doloribus voluptate.', '4157660', '3061.37', '0', 'v', '2008-01-27', '1980-07-01', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (28, 'EM', ' EG', '107902', 'h', 'si1', '1970-06-24', '1587713791', 'tempora', '2', 62, 53, 'molestiae', 'g', 'p', 'g', 'medium', ' faint', 'Explicabo dolorem molestias consequuntur distinctio dolor molestiae.', '6.98528', '5458.81', '0', 'v', '2009-03-16', '1994-12-17', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (29, 'EM', ' EG', '11832', 'd', 'fl', '1996-06-27', '1390833037', 'sunt', '1', 67, 67, 'et', 'ex', 'p', 'p', 'none', ' mb', 'Placeat voluptas architecto rem qui.', '536.92', '3650.04', '0', 'w', '1996-08-15', '1977-03-27', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (30, 'PC', ' EG', '4', 'e', 'vs2', '2011-05-29', '1985750724', 'a', '1', 63, 67, 'voluptatibus', 'f', 'p', 'p', 'small', ' sb', 'Possimus deleniti sit voluptatibus omnis occaecati numquam.', '890296', '1833.22', '0', 'w', '1983-06-15', '1997-11-25', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (31, 'PC', ' EG', '17', 'g', 'if', '1983-09-08', '1170833537', 'aliquid', '2', 61, 52, 'hic', 'f', 'g', 'vg', 'medium', ' faint', 'Non vitae consequuntur quo voluptas id.', '403.65', '32350.4', '0', 'v', '2000-04-13', '1991-08-28', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (32, 'PC', 'GIA', '20', 'e', 'vs1', '1985-01-29', '1235181906', 'vitae', '2', 64, 52, 'exercitationem', 'p', 'f', 'vg', 'none', 'none', 'Repellat ipsa inventore qui atque expedita non excepturi aperiam.', '31487200', '490.876', '0', 'w', '2001-03-21', '2010-08-22', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (33, 'PC', 'GIA', '25020', 'i', 'vs2', '2002-05-17', '1045107391', 'quas', '2', 65, 67, 'ad', 'f', 'p', 'p', 'large', 'vsb', 'Quo aut autem esse aliquid necessitatibus.', '346.968', '157615000', '0', 'w', '1973-02-08', '1970-02-26', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (34, 'PC', ' EG', '18037', 'h', 'vs1', '2005-10-15', '1495532790', 'facere', '1', 69, 68, 'minus', 'ex', 'g', 'g', 'none', 'vsb', 'Nihil et accusamus eos in.', '43059.6', '911.887', '0', 'v', '2001-02-19', '1989-04-09', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (35, 'BR', ' EG', '359020000', 'g', 'si2', '2007-11-28', '1450166735', 'illo', '1', 63, 51, 'quaerat', 'vg', 'ex', 'p', 'medium', ' faint', 'Et culpa nesciunt repellat totam minus quia.', '88297.8', '91473.7', '0', 'v', '2005-08-30', '1978-03-13', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (36, 'EM', ' EG', '5', 'h', 'vs2', '2004-02-13', '1644235512', 'qui', '2', 70, 60, 'aspernatur', 'vg', 'g', 'ex', 'medium', ' mb', 'Cupiditate voluptas corrupti et.', '194.559', '4395.82', '0', 'v', '1999-05-11', '2009-12-06', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (37, 'MQ', ' EG', '3395480', 'g', 'vvs1', '1998-01-21', '1771153081', 'et', '1', 66, 65, 'nesciunt', 'vg', 'f', 'g', 'small', 'vsb', 'Reprehenderit et enim autem saepe ipsam quia doloribus.', '6568310', '2640.64', '0', 'v', '1993-11-06', '1983-04-06', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (38, 'PC', 'GIA', '50', 'h', 'vs2', '1996-01-01', '1243649643', 'consequatur', '1', 56, 51, 'voluptatem', 'f', 'p', 'g', 'none', 'none', 'Quia nisi animi dolorem mollitia est.', '34387200', '902.896', '0', 'v', '2001-05-27', '1993-06-08', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (39, 'PC', ' EG', '210094', 'j', 'vs2', '1985-01-03', '1860866342', 'non', '2', 61, 64, 'dolor', 'vg', 'vg', 'p', 'none', ' sb', 'Est ipsa autem quae sit.', '396.073', '887.121', '0', 'w', '1988-01-24', '2010-12-12', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (40, 'EM', ' EG', '11160', 'f', 'fl', '1983-03-10', '1247398481', 'enim', '1', 54, 67, 'quia', 'g', 'g', 'ex', 'medium', 'vsb', 'Et commodi rerum rerum ratione earum enim.', '416370', '3437.95', '0', 'w', '1975-03-02', '2015-05-02', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (41, 'BR', ' EG', '28674500', 'e', 'fl', '1976-12-04', '1709196040', 'sed', '1', 60, 61, 'et', 'f', 'g', 'ex', 'medium', ' sb', 'Reprehenderit qui officiis dolore ducimus et.', '2345.43', '1573860', '0', 'v', '2009-08-16', '2002-02-01', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (42, 'EM', ' EG', '62490', 'j', 'fl', '1977-04-22', '1639333144', 'quia', '1', 58, 67, 'sint', 'ex', 'g', 'vg', 'large', ' sb', 'Officia cumque animi dolorem odit cupiditate et earum.', '498.652', '9014200', '0', 'w', '1999-08-28', '2015-05-26', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (43, 'MQ', 'GIA', '277929', 'i', 'vs2', '1992-12-21', '1350160787', 'ut', '1', 58, 52, 'labore', 'p', 'vg', 'p', 'large', 'none', 'Non aut provident doloribus id omnis.', '739.759', '4589.36', '0', 'w', '1992-10-11', '1986-01-03', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (44, 'MQ', 'GIA', '18226300', 'f', 'si1', '1979-02-06', '1925234996', 'quidem', '2', 63, 54, 'eum', 'p', 'g', 'ex', 'large', ' sb', 'Eius quo consequuntur consequatur cupiditate quibusdam enim vitae.', '390.589', '789881', '0', 'v', '1972-12-11', '1970-12-16', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (45, 'BR', 'GIA', '504012', 'g', 'vvs2', '1978-04-25', '1783279734', 'consequuntur', '2', 70, 57, 'delectus', 'vg', 'f', 'f', 'large', ' faint', 'Placeat at delectus nobis itaque.', '731.045', '3743.41', '0', 'w', '2005-11-20', '1980-05-09', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (46, 'EM', ' EG', '392642', 'j', 'if', '1972-08-07', '1766213726', 'consequatur', '1', 61, 70, 'ullam', 'ex', 'p', 'f', 'medium', 'none', 'Repellat accusantium odio esse enim dicta.', '517.156', '443359', '0', 'v', '1971-08-19', '2006-04-30', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (47, 'EM', ' EG', '812218', 'i', 'vs1', '2017-06-26', '1489443322', 'temporibus', '2', 61, 63, 'rerum', 'f', 'ex', 'g', 'small', ' faint', 'Accusantium doloremque nulla nam blanditiis.', '462175000', '7000.02', '0', 'w', '1994-03-07', '1994-04-10', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (48, 'PC', 'GIA', '152807000', 'j', 'si1', '1986-01-10', '1021811878', 'sed', '2', 56, 51, 'laborum', 'g', 'f', 'vg', 'small', ' faint', 'Illum temporibus eum soluta qui maiores et commodi.', '512800000', '7057.4', '0', 'w', '2004-03-16', '2014-03-06', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (49, 'MQ', 'GIA', '283038000', 'g', 'vs1', '1993-03-27', '1697232794', 'eius', '1', 60, 61, 'voluptas', 'vg', 'p', 'vg', 'small', ' faint', 'Eveniet quis alias fugit quis sint.', '728.192', '4345.52', '0', 'v', '2005-04-14', '1997-04-25', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (50, 'EM', ' EG', '26528', 'j', 'if', '1970-02-25', '1351297295', 'voluptas', '1', 68, 59, 'voluptatibus', 'vg', 'ex', 'ex', 'medium', ' sb', 'Ut ullam cumque omnis ex nulla consequatur consequatur.', '251227', '3311', '0', 'v', '1993-08-25', '1990-08-12', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (51, 'EM', ' EG', '3', 'e', 'vs1', '1986-10-12', '1409576138', 'ipsam', '1', 60, 56, 'esse', 'ex', 'g', 'vg', 'medium', ' faint', 'Sunt sit quia maxime officia.', '1137560', '235537', '0', 'w', '1986-04-16', '1972-02-11', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (52, 'MQ', ' EG', '39690700', 'j', 'vs2', '2008-05-22', '1055564128', 'doloribus', '2', 66, 61, 'quo', 'f', 'ex', 'ex', 'none', ' mb', 'Qui numquam est facilis eum.', '325.554', '3981.79', '0', 'v', '2009-08-26', '1987-12-03', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (53, 'MQ', 'GIA', '28312300', 'd', 'vs1', '2012-02-08', '1309425393', 'nostrum', '2', 67, 55, 'qui', 'vg', 'vg', 'ex', 'small', ' faint', 'Ab rerum expedita totam dolor pariatur incidunt.', '154.113', '2204220', '0', 'v', '1979-03-27', '2009-12-28', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (54, 'BR', 'GIA', '6', 'd', 'vs1', '2001-03-06', '1029460156', 'aut', '2', 56, 52, 'quae', 'p', 'f', 'vg', 'none', 'none', 'Neque et ab sit sapiente voluptas.', '308.32', '111.069', '0', 'w', '2001-06-06', '2009-01-05', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (55, 'BR', ' EG', '2130030', 'e', 'if', '1986-04-14', '1063389189', 'veritatis', '1', 55, 65, 'officia', 'vg', 'g', 'p', 'medium', 'none', 'Culpa dicta et vitae.', '1670230', '1190.2', '0', 'w', '1980-10-10', '1987-08-13', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (56, 'MQ', ' EG', '1', 'd', 'vs1', '1997-06-21', '1220652093', 'ut', '1', 58, 52, 'iure', 'f', 'vg', 'ex', 'large', ' sb', 'Iste minus et voluptatum rerum dolores dolor repellat.', '154.205', '4948.54', '0', 'v', '1983-01-16', '2000-04-22', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (57, 'EM', 'GIA', '195412000', 'd', 'fl', '2012-05-02', '1633050062', 'dolorum', '1', 54, 65, 'deleniti', 'g', 'vg', 'g', 'none', ' faint', 'Eaque et praesentium ut beatae voluptate.', '235.197', '53020.8', '0', 'v', '2015-11-12', '1998-03-27', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (58, 'BR', ' EG', '824', 'i', 'vs1', '2002-01-19', '1147372889', 'assumenda', '2', 53, 68, 'cumque', 'f', 'p', 'g', 'small', ' mb', 'Et blanditiis eaque nisi voluptatibus sit.', '506.718', '3935.51', '0', 'w', '1991-07-04', '1998-12-27', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (59, 'BR', ' EG', '17376', 'g', 'vvs1', '1988-09-25', '1141186662', 'temporibus', '1', 61, 55, 'iure', 'p', 'p', 'p', 'large', ' faint', 'Id ullam saepe qui veritatis velit tempora atque.', '150.954', '2513.82', '0', 'w', '2015-01-14', '1999-07-08', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (60, 'BR', ' EG', '4', 'h', 'fl', '1977-08-20', '1926682326', 'enim', '1', 61, 57, 'inventore', 'p', 'p', 'p', 'none', ' faint', 'Autem eligendi qui fugiat omnis voluptas.', '59.6153', '1098.71', '0', 'w', '1993-06-30', '1987-08-23', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (61, 'MQ', ' EG', '1334', 'd', 'vvs1', '2015-05-03', '1268962552', 'soluta', '1', 67, 63, 'deserunt', 'g', 'vg', 'ex', 'small', ' mb', 'Omnis facere explicabo minima ad consequatur.', '731.179', '12423.2', '0', 'v', '2006-08-26', '2001-04-26', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (62, 'EM', 'GIA', '1664', 'e', 'vvs2', '1972-08-31', '1016455409', 'quo', '2', 59, 61, 'expedita', 'vg', 'p', 'ex', 'medium', 'vsb', 'Repellat culpa excepturi totam libero nisi omnis.', '16.2102', '735003', '0', 'v', '2009-02-22', '2016-06-17', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (63, 'PC', ' EG', '842', 'f', 'vvs2', '1972-10-18', '1038301438', 'quisquam', '2', 63, 60, 'fugit', 'g', 'f', 'g', 'large', ' sb', 'Quis non sed quia et a.', '302.814', '4951.04', '0', 'v', '1971-04-18', '2008-10-14', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (64, 'PC', ' EG', '7682030', 'd', 'if', '1989-06-12', '1810747656', 'veniam', '1', 65, 62, 'quam', 'g', 'f', 'p', 'small', ' faint', 'Natus qui in qui labore saepe.', '4788460', '892.804', '0', 'v', '1978-01-05', '1978-02-18', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (65, 'BR', ' EG', '1797560', 'd', 'vs1', '1985-08-24', '1151217020', 'non', '2', 64, 64, 'sit', 'g', 'ex', 'p', 'large', 'vsb', 'Est qui amet eos est.', '2503320', '2669730', '0', 'v', '2007-11-18', '2010-11-19', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (66, 'EM', ' EG', '83', 'd', 'vvs1', '1994-11-12', '1584512748', 'aut', '2', 62, 68, 'quia', 'f', 'vg', 'ex', 'large', ' faint', 'Quis ut dolorum non ea qui natus.', '2213.73', '702869', '0', 'w', '1982-09-25', '1993-07-10', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (67, 'MQ', ' EG', '91706600', 'g', 'si1', '1975-11-03', '1169673021', 'consequuntur', '1', 70, 58, 'autem', 'f', 'ex', 'vg', 'large', 'none', 'Placeat culpa natus earum cum quam est cum.', '562.281', '4315.05', '0', 'v', '2006-06-10', '2008-12-05', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (68, 'EM', 'GIA', '144212000', 'e', 'vvs2', '2002-12-17', '1717353584', 'et', '1', 60, 63, 'et', 'vg', 'g', 'vg', 'none', 'vsb', 'Minus ut doloribus modi aut ex laudantium animi nam.', '23654300', '13207900', '0', 'v', '2007-02-08', '1997-10-15', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (69, 'PC', ' EG', '2880960', 'h', 'fl', '1983-02-17', '1186896726', 'dolorem', '1', 57, 53, 'quod', 'p', 'g', 'vg', 'large', ' mb', 'Quasi qui accusamus maiores fugit et consequuntur sunt doloribus.', '144.149', '1263.58', '0', 'v', '2016-07-25', '2009-01-02', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (70, 'MQ', 'GIA', '1195', 'i', 'si2', '1987-03-10', '1254789385', 'ab', '2', 63, 61, 'saepe', 'vg', 'f', 'g', 'large', 'vsb', 'Expedita quaerat eaque eos doloremque velit maiores.', '12183.5', '2236.87', '0', 'w', '2010-06-01', '1988-11-25', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (71, 'BR', 'GIA', '2', 'd', 'vs2', '2014-09-26', '1655934923', 'dignissimos', '2', 51, 50, 'id', 'f', 'g', 'p', 'none', ' sb', 'Ipsa placeat voluptates sit ullam sapiente voluptatem aliquam.', '395.106', '350418000', '0', 'v', '2014-06-16', '1981-06-12', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (72, 'EM', 'GIA', '5234790', 'j', 'fl', '1992-02-12', '1472162873', 'ea', '1', 61, 59, 'et', 'p', 'p', 'ex', 'small', ' faint', 'Ipsum qui qui nihil nihil sit.', '3288.28', '4185.67', '0', 'w', '1970-02-11', '1987-09-01', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (73, 'BR', 'GIA', '24133', 'h', 'si2', '2007-07-22', '1347994672', 'dolores', '1', 59, 53, 'sed', 'f', 'g', 'p', 'small', ' sb', 'Rem rerum autem qui sit vitae fugit.', '82921700', '124326', '0', 'v', '1986-12-26', '1983-04-15', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (74, 'BR', 'GIA', '176114000', 'j', 'if', '2003-10-11', '1398992749', 'omnis', '1', 62, 59, 'qui', 'g', 'p', 'f', 'large', 'vsb', 'Magni quis occaecati non quo voluptas dolores enim numquam.', '114.138', '3147660', '0', 'w', '1994-05-20', '1999-10-18', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (75, 'BR', 'GIA', '34066400', 'j', 'fl', '2006-09-17', '1808734742', 'facere', '2', 69, 64, 'excepturi', 'f', 'p', 'f', 'none', ' mb', 'Ut doloribus minima error odio autem qui eligendi.', '5908.09', '40234.3', '0', 'v', '2009-05-27', '1970-08-26', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (76, 'BR', ' EG', '481458', 'g', 'vvs2', '2004-03-31', '1065025680', 'numquam', '1', 67, 70, 'omnis', 'f', 'g', 'vg', 'none', ' sb', 'Non blanditiis aut consequuntur distinctio.', '485.108', '4293.81', '0', 'w', '2001-11-14', '2010-02-17', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (77, 'MQ', 'GIA', '6', 'd', 'if', '2013-02-13', '1161641319', 'perspiciatis', '2', 58, 58, 'deserunt', 'p', 'vg', 'p', 'small', 'vsb', 'Earum recusandae non eius quam.', '530.518', '4798.65', '0', 'v', '2003-05-15', '1971-03-06', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (78, 'MQ', ' EG', '3728920', 'h', 'vs1', '2001-05-21', '1444623840', 'molestiae', '2', 54, 56, 'aspernatur', 'g', 'vg', 'ex', 'none', ' mb', 'Ipsa porro dolorum ut ut aut a.', '3634.01', '538864000', '0', 'v', '2014-01-09', '1982-08-27', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (79, 'EM', ' EG', '12467200', 'f', 'if', '2012-08-02', '1684076472', 'sapiente', '1', 69, 70, 'fuga', 'g', 'vg', 'vg', 'none', ' mb', 'Nulla aspernatur doloribus illo perspiciatis aut modi recusandae quia.', '315847', '2309.39', '0', 'w', '2014-02-09', '1989-02-06', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (80, 'MQ', ' EG', '5', 'i', 'vs1', '1978-01-26', '1897102830', 'sed', '2', 61, 55, 'unde', 'g', 'f', 'f', 'none', 'vsb', 'Dicta quos dolores debitis dicta in reprehenderit.', '963784', '622261', '0', 'w', '1972-01-07', '1974-03-07', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (81, 'BR', 'GIA', '14808', 'd', 'vvs1', '1982-06-14', '1913293100', 'ut', '2', 50, 70, 'at', 'g', 'g', 'ex', 'small', ' sb', 'Mollitia qui ab reiciendis.', '292.106', '3944', '0', 'v', '1988-12-24', '1974-02-14', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (82, 'MQ', 'GIA', '613766', 'i', 'vs1', '2004-01-15', '1378237279', 'harum', '1', 69, 65, 'aliquid', 'vg', 'f', 'g', 'medium', 'none', 'Culpa sit eveniet est quos fugiat magni.', '131.111', '5144.05', '0', 'w', '1987-02-26', '2012-09-19', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (83, 'PC', ' EG', '7', 'j', 'fl', '2014-06-13', '1787495464', 'sint', '2', 69, 66, 'est', 'f', 'g', 'vg', 'large', 'vsb', 'Esse deleniti delectus numquam est magnam quisquam.', '1560.37', '2613.68', '0', 'w', '1999-07-27', '1984-04-22', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (84, 'BR', 'GIA', '9094', 'j', 'if', '1979-06-01', '1559192539', 'quia', '1', 70, 59, 'perspiciatis', 'f', 'g', 'f', 'none', 'vsb', 'Omnis minima culpa voluptatem doloremque quibusdam repudiandae.', '85316600', '15726.8', '0', 'w', '2013-09-12', '2018-02-04', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (85, 'BR', ' EG', '80875500', 'g', 'vvs1', '2005-10-23', '1989606429', 'molestiae', '2', 67, 60, 'id', 'f', 'vg', 'ex', 'small', ' mb', 'Fuga ullam et qui ut.', '416.656', '4997.99', '0', 'v', '1971-02-07', '1984-05-29', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (86, 'PC', 'GIA', '1054', 'f', 'si2', '1989-12-10', '1941836747', 'sed', '2', 53, 52, 'magni', 'g', 'g', 'f', 'large', 'vsb', 'Nisi dolorem nemo totam qui.', '2731.86', '3783.26', '0', 'v', '1985-06-29', '1982-12-14', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (87, 'EM', ' EG', '10', 'i', 'vs2', '1982-01-27', '1036200829', 'aspernatur', '2', 60, 70, 'eaque', 'vg', 'p', 'p', 'large', 'vsb', 'Perspiciatis et quo ea exercitationem nihil.', '27161.1', '2371.2', '0', 'v', '1978-02-11', '2006-10-08', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (88, 'MQ', ' EG', '87333000', 'h', 'vvs1', '1991-03-05', '1672248688', 'qui', '2', 60, 58, 'illum', 'f', 'f', 'g', 'small', 'vsb', 'Eligendi animi dolore autem veritatis tempora.', '3283550', '389.331', '0', 'w', '1990-06-02', '1981-07-20', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (89, 'MQ', 'GIA', '1244000', 'd', 'vs2', '1990-12-17', '1793193223', 'ducimus', '2', 58, 67, 'animi', 'vg', 'ex', 'ex', 'none', ' sb', 'Molestiae voluptatibus voluptatem velit.', '4168880', '103107000', '0', 'w', '2001-12-19', '1972-06-20', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (90, 'PC', ' EG', '2522170', 'i', 'vvs1', '2015-03-01', '1671137586', 'laudantium', '1', 69, 59, 'voluptates', 'vg', 'vg', 'f', 'small', 'none', 'Nostrum est nihil voluptas repellendus.', '174.617', '18598300', '0', 'w', '1977-07-02', '1971-05-17', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (91, 'PC', 'GIA', '261111', 'e', 'vvs2', '1989-09-02', '1023012728', 'fugit', '2', 54, 70, 'quia', 'f', 'f', 'p', 'large', ' faint', 'Qui officia qui quo harum est.', '20251.7', '3483.7', '0', 'v', '1990-12-24', '2012-06-02', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (92, 'PC', 'GIA', '221753000', 'f', 'vvs2', '2015-02-14', '1797525006', 'maxime', '2', 51, 68, 'in', 'g', 'g', 'vg', 'large', ' faint', 'Eos autem deleniti modi.', '583401000', '48918.8', '0', 'v', '1985-10-28', '1988-12-07', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (93, 'EM', ' EG', '19669', 'i', 'vs2', '2012-02-28', '1113657008', 'doloribus', '1', 64, 70, 'enim', 'ex', 'g', 'g', 'medium', ' sb', 'Porro quia nulla consequatur dolorem.', '108.991', '1681.87', '0', 'w', '1999-11-21', '2006-03-10', 'w', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (94, 'PC', ' EG', '318', 'g', 'vs1', '1977-01-05', '1635600454', 'quod', '2', 66, 51, 'qui', 'ex', 'vg', 'p', 'large', ' mb', 'Harum et neque ullam voluptatem.', '366.521', '14528300', '0', 'w', '1990-01-28', '2006-09-14', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (95, 'PC', ' EG', '832', 'd', 'vvs2', '2006-11-25', '1101579194', 'molestias', '2', 52, 65, 'illo', 'ex', 'vg', 'f', 'small', 'vsb', 'Commodi sit consectetur ullam adipisci non impedit molestiae ea.', '14574.6', '2073410', '0', 'w', '2002-04-09', '1997-04-30', 'v', 'round', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (96, 'BR', 'GIA', '5', 'e', 'vs1', '2001-04-17', '1103960395', 'id', '1', 57, 58, 'quae', 'f', 'p', 'g', 'large', ' mb', 'Illum nemo veniam non magni.', '165.071', '4544.9', '0', 'w', '2015-04-16', '1997-05-11', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (97, 'EM', 'GIA', '2', 'f', 'vs1', '2016-08-18', '1967926625', 'cupiditate', '2', 60, 50, 'quidem', 'f', 'p', 'g', 'large', 'vsb', 'Dignissimos aspernatur ut id aut.', '3375670', '579.16', '0', 'w', '1980-04-25', '1988-03-08', 'w', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (98, 'PC', 'GIA', '3', 'e', 'vs2', '2005-08-11', '1713505104', 'voluptates', '1', 56, 63, 'est', 'g', 'p', 'g', 'small', 'vsb', 'Dignissimos maiores eligendi in atque qui praesentium possimus.', '51.0129', '409513000', '0', 'w', '2017-03-15', '1980-07-07', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (99, 'BR', 'GIA', '351812000', 'f', 'si2', '1974-06-28', '1672411486', 'recusandae', '2', 68, 53, 'et', 'f', 'g', 'f', 'small', ' mb', 'Voluptatum explicabo cumque et.', '3191.27', '81869600', '0', 'v', '1979-07-09', '1993-11-17', 'v', ' pear', '0');
INSERT INTO `round_diamonds` (`key_id`, `shape`, `lab`, `size`, `color`, `clarity`, `giadate`, `gianumber`, `measurements`, `ratio`, `depth`, `table`, `girdle`, `cut`, `polish`, `symmetry`, `culet`, `fluorescence`, `comments`, `pricepercarat`, `orgprice`, `disc`, `person`, `datebought`, `datesold`, `soldby`, `rapaport_shape`, `orig_disc`) VALUES (100, 'BR', ' EG', '71304', 'e', 'vs2', '1975-11-19', '1730048537', 'corporis', '2', 66, 57, 'magnam', 'g', 'p', 'ex', 'medium', ' faint', 'Harum perferendis id ut voluptas repellat.', '96760.4', '1025390', '0', 'w', '1989-10-21', '2015-06-29', 'v', 'round', '0');


